Traceback (most recent call last):
  File "./vec-test.py", line 6, in <module>
    @cuda.jit('float32(float32[:])', device=True)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/cuda/decorators.py", line 104, in device_jit
    debug=debug)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/cuda/compiler.py", line 149, in compile_device
    return DeviceFunction(pyfunc, return_type, args, inline=True, debug=False)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/cuda/compiler.py", line 180, in __init__
    debug=self.debug, inline=self.inline)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/cuda/compiler.py", line 51, in compile_cuda
    locals={})
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler.py", line 941, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler.py", line 372, in compile_extra
    return self._compile_bytecode()
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler.py", line 872, in _compile_bytecode
    return self._compile_core()
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler.py", line 859, in _compile_core
    res = pm.run(self.status)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler.py", line 253, in run
    raise patched_exception
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler.py", line 244, in run
    stage()
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler.py", line 500, in stage_nopython_frontend
    self.locals)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler.py", line 1043, in type_inference_stage
    infer.build_constraint()
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/typeinfer.py", line 817, in build_constraint
    self.constrain_statement(inst)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/typeinfer.py", line 1096, in constrain_statement
    self.typeof_assign(inst)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/typeinfer.py", line 1159, in typeof_assign
    self.typeof_global(inst, inst.target, value)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/typeinfer.py", line 1256, in typeof_global
    typ = self.resolve_value_type(inst, gvar.value)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/typeinfer.py", line 1180, in resolve_value_type
    raise TypingError(msg, loc=inst.loc)
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Untyped global name 'numba': cannot determine Numba type of <class 'numba.ir.UndefinedType'>

File "vec-test.py", line 8:
def testfoo(x):
	f = numba.float32[:]
 ^

srun: error: gpu-0-0: task 0: Exited with exit code 1
