Traceback (most recent call last):
  File "./vec-test.py", line 6, in <module>
    @cuda.jit('float32(float32[:])', device=True)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/cuda/decorators.py", line 104, in device_jit
    debug=debug)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/cuda/compiler.py", line 149, in compile_device
    return DeviceFunction(pyfunc, return_type, args, inline=True, debug=False)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/cuda/compiler.py", line 180, in __init__
    debug=self.debug, inline=self.inline)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/cuda/compiler.py", line 51, in compile_cuda
    locals={})
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler.py", line 941, in compile_extra
    return pipeline.compile_extra(func)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler.py", line 372, in compile_extra
    return self._compile_bytecode()
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler.py", line 872, in _compile_bytecode
    return self._compile_core()
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler.py", line 859, in _compile_core
    res = pm.run(self.status)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler.py", line 253, in run
    raise patched_exception
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler.py", line 244, in run
    stage()
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler.py", line 500, in stage_nopython_frontend
    self.locals)
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/compiler.py", line 1044, in type_inference_stage
    infer.propagate()
  File "/home/jmcates/miniconda3/envs/zmcint/lib/python3.6/site-packages/numba/typeinfer.py", line 861, in propagate
    raise errors[0]
numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Invalid use of Function(<built-in function setitem>) with argument(s) of type(s): (tuple(int64 x 10), int64, float64)
 * parameterized
In definition 0:
    All templates rejected with literals.
In definition 1:
    All templates rejected without literals.
In definition 2:
    All templates rejected with literals.
In definition 3:
    All templates rejected without literals.
In definition 4:
    All templates rejected with literals.
In definition 5:
    All templates rejected without literals.
This error is usually caused by passing an argument of a type that is unsupported by the named function.
[1] During: typing of setitem at ./vec-test.py (12)

File "vec-test.py", line 12:
def testfoo(x):
    <source elided>
		for i in range(1,10):
			f[i] = math.sin((x[0]+x[1])/i)
   ^

srun: error: gpu-0-0: task 0: Exited with exit code 1
